PROCESS BEFORE OUTPUT.
  MODULE status_0300.
  MODULE pbo_0300.
  CALL SUBSCREEN g_sub_dynpro INCLUDING sy-repid '0301'.

PROCESS AFTER INPUT.
  CALL SUBSCREEN g_sub_dynpro.
  MODULE user_command_0300.
