PROCESS BEFORE OUTPUT.
 MODULE LISTE_INITIALISIEREN.
 LOOP AT EXTRACT WITH CONTROL
  TCTRL_ZBDC_FGUID_BUP CURSOR NEXTLINE.
   MODULE LISTE_SHOW_LISTE.
 ENDLOOP.
*
PROCESS AFTER INPUT.
 MODULE LISTE_EXIT_COMMAND AT EXIT-COMMAND.
 MODULE LISTE_BEFORE_LOOP.
 LOOP AT EXTRACT.
   MODULE LISTE_INIT_WORKAREA.
   CHAIN.
    FIELD ZBDC_FGUID_BUP-TCODE .
    FIELD ZBDC_FGUID_BUP-STAGING_FIELD .
    FIELD ZBDC_FGUID_BUP-BUSINESS_GROUP .
    FIELD ZBDC_FGUID_BUP-EXCEL_COLUMN .
    FIELD ZBDC_FGUID_BUP-BUSINESS_MEANING .
    FIELD ZBDC_FGUID_BUP-REQUIRED_FLAG .
    FIELD ZBDC_FGUID_BUP-EXAMPLE_VALUE .
    FIELD ZBDC_FGUID_BUP-DEPENDENCY .
    FIELD ZBDC_FGUID_BUP-VALIDATION_RULE .
    FIELD ZBDC_FGUID_BUP-DISPLAY_ORDER .
    FIELD ZBDC_FGUID_BUP-ACTIVE_FLAG .
    MODULE SET_UPDATE_FLAG ON CHAIN-REQUEST.
   ENDCHAIN.
   FIELD VIM_MARKED MODULE LISTE_MARK_CHECKBOX.
   CHAIN.
    FIELD ZBDC_FGUID_BUP-TCODE .
    FIELD ZBDC_FGUID_BUP-STAGING_FIELD .
    MODULE LISTE_UPDATE_LISTE.
   ENDCHAIN.
 ENDLOOP.
 MODULE LISTE_AFTER_LOOP.
