PROCESS BEFORE OUTPUT.
 MODULE LISTE_INITIALISIEREN.
 LOOP AT EXTRACT WITH CONTROL
  TCTRL_ZBDC_SCT_DEF_BUP CURSOR NEXTLINE.
   MODULE LISTE_SHOW_LISTE.
 ENDLOOP.
*
PROCESS AFTER INPUT.
 MODULE LISTE_EXIT_COMMAND AT EXIT-COMMAND.
 MODULE LISTE_BEFORE_LOOP.
 LOOP AT EXTRACT.
   MODULE LISTE_INIT_WORKAREA.
   CHAIN.
    FIELD ZBDC_SCT_DEF_BUP-TCODE .
    FIELD ZBDC_SCT_DEF_BUP-STEP_SEQ .
    FIELD ZBDC_SCT_DEF_BUP-IS_NEW_SCREEN .
    FIELD ZBDC_SCT_DEF_BUP-FIELD_NAME .
    FIELD ZBDC_SCT_DEF_BUP-VALUE_TYPE .
    FIELD ZBDC_SCT_DEF_BUP-STATIC_VALUE .
    FIELD ZBDC_SCT_DEF_BUP-SOURCE_COLUMN .
    FIELD ZBDC_SCT_DEF_BUP-ROW_TYPE .
    FIELD ZBDC_SCT_DEF_BUP-PROGRAM_NAME .
    FIELD ZBDC_SCT_DEF_BUP-DYNPRO_NO .
    MODULE SET_UPDATE_FLAG ON CHAIN-REQUEST.
   ENDCHAIN.
   FIELD VIM_MARKED MODULE LISTE_MARK_CHECKBOX.
   CHAIN.
    FIELD ZBDC_SCT_DEF_BUP-TCODE .
    FIELD ZBDC_SCT_DEF_BUP-STEP_SEQ .
    MODULE LISTE_UPDATE_LISTE.
   ENDCHAIN.
 ENDLOOP.
 MODULE LISTE_AFTER_LOOP.
